language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

matrix:
    include:
        - php: hhvm
          dist: trusty
          sudo: required

script:
    - vendor/bin/phug-dev check --report --coverage-php-version=5.6

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z

env:
  - TRAVIS_NODE_VERSION="7"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: b1735dad2eff66b6e6f9c3fa730459f67303626a6b837f1bd1d8dd1adb3b7065
